name: Testing Secret variables
on:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  test_context_variables_with_secret:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: "Checking secrets variable"
        run: |
          echo "Secrets value : ${{secrets.MY_SECRET_KEY}}"
